language: php
dist: xenial
sudo: false
php:
    - 7.2
    - 7.3
    - 7.4

addons:
    chrome: stable

cache:
    directories:
        - $HOME/.composer/cache/files

matrix:
    fast_finish: true

before_install:
    - mv ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini{,.disabled} || echo "xdebug not available"
    - composer self-update --2 -q

install:
    - COMPOSER_MEMORY_LIMIT=-1 composer update
    - ./bin/console bolt:info
    - nvm install 12.5
    - npm ci
    - mkdir -p ./var/log/e2e-reports/report/features/
    - touch ./var/log/e2e-reports/report/features/.gitkeep

before_script:
    # build assets
    - npm run build
    # prepare web server for e2e tests
    - ./bin/console doctrine:database:create
    - ./bin/console doctrine:schema:create
    - ./bin/console doctrine:fixtures:load --group=without-images -n
    - ./bin/console server:start 127.0.0.1:8088
    # test if web server works
    - sleep 3
    - wget "http://127.0.0.1:8088/bolt/login"
    - export PATH=$PATH:$PWD/vendor/bin

script:
    # run PHP Unit
    - ./vendor/bin/phpunit

    # run API tests
    - make behat-api-quiet

    # run JS e2e tests
    - travis_retry make db-reset-without-images && make behat-js-quiet

    # Upload Behat logs
    - ./vendor/bin/upload-textfiles "var/log/behat-reports/*.log"
