# This file defines role-based access control for your Bolt site.
# Before making any modifications to this file, make sure you've thoroughly
# read the documentation at https://docs.bolt.cm/configuration/permissions
# and understand the consequences of making uninformed changes to the roles and
# permissions.

# These permissions are the 'global' permissions; these are not tied
# to any content types, but rather apply to global, non-content activity in
# Bolt's backend. Most of these permissions map directly to backend routes;
# keep in mind, however, that routes do not always correspond to URL paths 1:1.
# The default set defined here is appropriate for most sites, so most likely,
# you will not have to change it.
# Also note that the 'editcontent' and 'overview' routes are special-cased
# inside the code, so they don't appear here.
global:
    about: [ IS_AUTHENTICATED_ANONYMOUSLY ] # view the 'About Bolt' page
#    checks: [ admin, developer ]
    clearcache: [ ROLE_ADMIN, ROLE_DEVELOPER ]
#    contentaction: [ ROLE_EDITOR, admin, developer ]
    dashboard: [ IS_AUTHENTICATED_FULLY ]
#    dbcheck: [ admin, developer ]
#    dbupdate: [ admin, developer ]
#    dbupdate_result: [ admin, developer ]
    extensions: [ ROLE_DEVELOPER ]
#    extensions:config: [ developer ]
    
    # these control /bolt/file-edit and /bolt/filemanager -> combined create/read/update/delete permission
    # the part after the files: is the 'location' where the files are part of
    managefiles:config: [ ROLE_DEVELOPER ] # all configuration yml files /bolt/filemanager/config and /bolt/file-edit/config?file=/bolt/menu.yaml
    managefiles:files: [ ROLE_DEVELOPER ]
    managefiles:themes: [ ROLE_DEVELOPER ]
    
#    prefill: [ developer ]
    profile: [ IS_AUTHENTICATED_FULLY ] # edit own profile
#    settings: [ admin, developer, everyone ]
#    translation: [ developer ]
#    useraction: [ admin, developer ] # enable/disable/delete
    useredit: [ admin, developer ] # user settings
#    users: [ admin, developer ] # view user overview
#    roles: [ admin, developer ] # view the roles overview
#    maintenance-mode: [ everyone ] # view the frontend when in maintenance mode
    omnisearch: [ IS_AUTHENTICATED_ANONYMOUSLY ]
#    # Access to the various logs
#    changelog: [ admin, developer, chief-editor ]
    systemlog: [ ROLE_ADMIN, ROLE_DEVELOPER ]
# NEW ???
    bulk_operations: [ ROLE_CHIEF_EDITOR ]
    fixtures: [ ROLE_DEVELOPER ] # <-- controller route exists, but fixtures support hasn't been implemented yet 
    kitchensink: [ ROLE_DEVELOPER ]


# For content type related actions, permissions can be set individually for
# each content type. For this, we define three groups of permission sets.
# The 'contenttype-all' permission sets *overrides*; any roles specified here
# will grant a permission for all content types, regardless of the rest of this
# section.
# The 'contenttype-default' contains rules that are used when the desired
# content type does not define a rule for this permission itself.
# The 'contenttypes' section specifies permissions for individual content
# types.
#
# To understand how this works, it may be best to follow the permission checker
# through its decision-making process.
#
# First, it checks whether the current user is in the "root" role; if so, it
# short-circuits and always grants anything unconditionally.
#
# Otherwise, it checks whether any of the current user's roles match any of the
# roles in contenttype-all/{permission}. If so, the search is over, and the
# permission can be granted.
#
# The next step is to find contenttypes/{contenttype}/{permission}. If it is
# found, then the permission can be granted if and only if any of the user's
# roles match any role in contenttypes/{contenttype}/{permission}.
#
# If either contenttypes/{contenttype} or
# contenttypes/{contenttype}/{permission} is absent, the permission checker
# uses contenttype-default/{permission} instead. If any role exists in both the
# user's roles and contenttype-default/{permission}, the permission can be
# granted.
#
# Note especially that an *empty* set of roles in the contenttype section means
# something else than the *absence* of the permission. If the permission is
# defined with an empty role list, it overrides the role list in
# contenttype-default; but if the permission is not mentioned, the
# corresponding entry in contenttype-default applies.
#
# The following permissions are available on a per-contenttype basis:
#
# - edit: allows updating existing records
# - create: allows creating new records
# - publish: allows changing the status of a record to "published", as well as
#            scheduling a record for future publishing
# - depublish: allows changing the status of a record from "published"
# - delete: allows (hard) deletion of records
# - change-ownership: allows changing a record's owner. Note that ownership may
#                     grant additional permissions on a record, so this
#                     permission can indirectly enable users more permissions
#                     in ways that may not be immediately obvious.
# - view: allows viewing records in the backend (listings, content/fields)



# these permissions will be added to _all_ contenttypes, they can not be overridden
contenttype-all:
    edit: [ ROLE_ADMIN ]
    create: [ ROLE_ADMIN ]
    publish: [ ROLE_ADMIN ]
    depublish: [ ROLE_ADMIN ]
    delete: [ ROLE_ADMIN ]
    change-ownership: [ ROLE_ADMIN ]
    view: [ ROLE_ADMIN ] # = show in menu, show listings, open 'edit' view without actually being able to edit, any of the other permissions always imply 'view'

# these permissions are used as a default for contenttypes 
# you can override these settings per contenttype by adding it to the `contenttypes:` array
contenttype-default:
    edit: [ ROLE_CHIEF_EDITOR ]
    create: [ ROLE_CHIEF_EDITOR ]
    change-ownership: [ CONTENT_OWNER ] # <-- how to handle chance-ownership permission without 'edit'?
    view: [ ROLE_CHIEF_EDITOR ]
#    view: [ IS_AUTHENTICATED_FULLY ]
#    show-in-menu: [ IS_AUTHENTICATED_FULLY ] # <-- not a useful permission after all


contenttypes:

# This is an example of how to define Contenttype specific permissions
#
# contenttypes:
#    # Keys in this dictionary map to keys in the contenttypes.yml specification.
#    showcases:
#        # Rules defined here *override* rules defined in contenttype-default,
#        # but *add* to rules in contenttype-all. This means that permissions
#        # granted through contenttype-all cannot be revoked here, merely
#        # amended.
#
#        # Only the Admin and Chief Editor are allowed to edit records
#        edit: [ ROLE_CHIEF_EDITOR ]
#        create: [ ROLE_CHIEF_EDITOR ]
#        publish: [ ROLE_CHIEF_EDITOR ]
#        depublish: [ ROLE_CHIEF_EDITOR ]
#        delete: [ ROLE_CHIEF_EDITOR ]
#        show-in-menu: [ ROLE_CHIEF_EDITOR ]
    pages:
        edit: [ ROLE_EDITOR ]
        create: [ ROLE_EDITOR ]
        change-ownership: [ CONTENT_OWNER ]
        view: [ ROLE_USER ]
#        view: [ IS_AUTHENTICATED_FULLY ]
#        show-in-menu: [ IS_AUTHENTICATED_FULLY ] #<-- not useful after all
