name: Unit Tests

on: [push, pull_requests]

jobs:
    unittests:
        strategy:
            fail-fast: true
            matrix:
                php: ['7.2', '7.3', '7.4']
                node-version: ['12.5']
        name: PHP Unit tests
            runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: nanasess/setup-chromedriver@master
            - uses: actions/setup-node@v1
              with:
                node-version: ${{ matrix.node-version }}
            - name: Run phpunit
              run: ./vendor/bin/phpunit
